language: c

sudo: false

os:
  - linux
  - osx

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit
    - LUA=luajit2.0
    - LUA=luajit2.1

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install busted
  - luarocks make luasystem-scm-0.rockspec

script: busted spec

branches:
  only:
    - master

notifications:
  email: false
